### ISSUE TITLE
Calendar icon shows wrong date and month

### ISSUE THREAD

**Issue by lamyergeier** [k3b/calef#3]
In the message Calendar icon shows wrong date and month. Is it possible to change the icon matching the event date and time. If not could you please give an option to exclude the icon. It can cause unnecessary confusion!

I have added this to my calendar 
📅Tue 4 July 2023 08:00 Get clothes from washing machine

**Comment by k3b** [comment]
@ lamyergeier  You are right. the "Calendar icon" does not correspond to the calendar-date.

Unfortunately "Calendar icon" is a predefined "emoji-character" that is not modifyable.

I cannot fix this :-(

**Comment by lamyergeier** [comment]
May be remove that emoji as it is confusing
